---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slurm-kunluncloud-com-v1alpha1-cluster
  failurePolicy: Fail
  name: vcluster-v1alpha1.kb.io
  rules:
  - apiGroups:
    - slurm.kunluncloud.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
