apiVersion: v2
name: slurm-operator
description: A Helm chart for slurm-operator
home: https://github.com/troila-klcloud/slurm-operator
type: application
version: 0.0.3
appVersion: v1.0.8
maintainers:
  - email: klcsales@troila.com
    name: klcloud
