replicaCount: 3
image:
  repository: registry.cn-hangzhou.aliyuncs.com/troila-klcloud/slurm-operator
  pullPolicy: IfNotPresent
  tag: v1.0.1
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
ldap:
  uri: ldap://openldap.openldap.svc.cluster.local
  defaultAuthtok: Not@SecurePassw0rd
  defaultAuthtokType: password
  defaultBindDn: cn=admin,dc=example,dc=org
  searceBase: dc=example,dc=org
  skipInsecureTls: true
podAnnotations:
  kubectl.kubernetes.io/default-container: manager
