# This rule is not used by the project slurm-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to slurm.kunluncloud.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: slurm-operator
    app.kubernetes.io/managed-by: kustomize
  name: cluster-viewer-role
rules:
- apiGroups:
  - slurm.kunluncloud.com
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - slurm.kunluncloud.com
  resources:
  - clusters/status
  verbs:
  - get
