//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountingNodeSpec) DeepCopyInto(out *AccountingNodeSpec) {
	*out = *in
	in.SlurmdbdContainer.DeepCopyInto(&out.SlurmdbdContainer)
	in.MungeContainer.DeepCopyInto(&out.MungeContainer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountingNodeSpec.
func (in *AccountingNodeSpec) DeepCopy() *AccountingNodeSpec {
	if in == nil {
		return nil
	}
	out := new(AccountingNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterList.
func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	in.LoginNode.DeepCopyInto(&out.LoginNode)
	in.CtrlNode.DeepCopyInto(&out.CtrlNode)
	in.AccountingNode.DeepCopyInto(&out.AccountingNode)
	in.WebNode.DeepCopyInto(&out.WebNode)
	in.Database.DeepCopyInto(&out.Database)
	if in.ComputingNodeSets != nil {
		in, out := &in.ComputingNodeSets, &out.ComputingNodeSets
		*out = make([]ComputingNodeSetSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodStatuses != nil {
		in, out := &in.PodStatuses, &out.PodStatuses
		*out = make([]PodStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonContainerSpec) DeepCopyInto(out *CommonContainerSpec) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonContainerSpec.
func (in *CommonContainerSpec) DeepCopy() *CommonContainerSpec {
	if in == nil {
		return nil
	}
	out := new(CommonContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputingNodeSetSpec) DeepCopyInto(out *ComputingNodeSetSpec) {
	*out = *in
	in.SlurmdContainer.DeepCopyInto(&out.SlurmdContainer)
	in.SssdContainer.DeepCopyInto(&out.SssdContainer)
	in.MungeContainer.DeepCopyInto(&out.MungeContainer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputingNodeSetSpec.
func (in *ComputingNodeSetSpec) DeepCopy() *ComputingNodeSetSpec {
	if in == nil {
		return nil
	}
	out := new(ComputingNodeSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CtrlNodeSpec) DeepCopyInto(out *CtrlNodeSpec) {
	*out = *in
	in.SlurmCtldContainer.DeepCopyInto(&out.SlurmCtldContainer)
	in.SssdContainer.DeepCopyInto(&out.SssdContainer)
	in.MungeContainer.DeepCopyInto(&out.MungeContainer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CtrlNodeSpec.
func (in *CtrlNodeSpec) DeepCopy() *CtrlNodeSpec {
	if in == nil {
		return nil
	}
	out := new(CtrlNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBStroage) DeepCopyInto(out *DBStroage) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBStroage.
func (in *DBStroage) DeepCopy() *DBStroage {
	if in == nil {
		return nil
	}
	out := new(DBStroage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSpec.
func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginNodeSpec) DeepCopyInto(out *LoginNodeSpec) {
	*out = *in
	in.SshdContainer.DeepCopyInto(&out.SshdContainer)
	in.SssdContainer.DeepCopyInto(&out.SssdContainer)
	in.MungeContainer.DeepCopyInto(&out.MungeContainer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginNodeSpec.
func (in *LoginNodeSpec) DeepCopy() *LoginNodeSpec {
	if in == nil {
		return nil
	}
	out := new(LoginNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodStatus) DeepCopyInto(out *PodStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.PodCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodStatus.
func (in *PodStatus) DeepCopy() *PodStatus {
	if in == nil {
		return nil
	}
	out := new(PodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebNodeSpec) DeepCopyInto(out *WebNodeSpec) {
	*out = *in
	in.WebContainer.DeepCopyInto(&out.WebContainer)
	in.SssdContainer.DeepCopyInto(&out.SssdContainer)
	in.MungeContainer.DeepCopyInto(&out.MungeContainer)
	in.InitSqlContainer.DeepCopyInto(&out.InitSqlContainer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebNodeSpec.
func (in *WebNodeSpec) DeepCopy() *WebNodeSpec {
	if in == nil {
		return nil
	}
	out := new(WebNodeSpec)
	in.DeepCopyInto(out)
	return out
}
