name: Build slurm operator container image

on:
  push:
    tags:
    - 'v*'
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get changed files
      if: github.event_name == 'pull_request'
      id: changed-files
      uses: tj-actions/changed-files@v46
      with:
        files: |
          ./*.go
          Dockerfile

    - name: Login to aliyun acr
      if: github.event_name == 'pull_request' || steps.changed-files.outputs.any_changed == 'true'
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ vars.ALIYUN_ACR_USER }}
        password: ${{ secrets.ALIYUN_ACR_TOKEN }}

    - name: Set up QEMU
      if: github.event_name != 'pull_request' || steps.changed-files.outputs.any_changed == 'true'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: github.event_name != 'pull_request' || steps.changed-files.outputs.any_changed == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      if: github.event_name != 'pull_request' || steps.changed-files.outputs.any_changed == 'true'
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: registry.cn-hangzhou.aliyuncs.com/troila-klcloud/slurm-operator

    - name: Build and push
      if: github.event_name != 'pull_request' || steps.changed-files.outputs.any_changed == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
